# Deploy React portfolio to GitHub Pages using gh-pages
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for deployment
permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

jobs:
  # Build and Deploy job
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://TeshiOAO.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for gh-pages
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --prefer-offline
        
      - name: Build project
        run: npm run build
        
      - name: Configure Git for deployment
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist -u "github-actions[bot] <github-actions[bot]@users.noreply.github.com>" -r https://x-access-token:${{ secrets.PAGE_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          PAGE_TOKEN: ${{ secrets.PAGE_TOKEN }}
